#!/usr/bin/env python3
"""Post-build install script for the Emacs Meson build.

Handles items that need build-tree artefacts to exist on disk:

  * etc/DOC          -- generated by src/meson.build's etc-DOC target
                        (Makefile.in:701-714 install-etcdoc).
  * native-lisp/     -- *.eln tree from native-compilation
                        (Makefile.in:846-859 install-eln).
  * subdirs.el       -- generated under share/emacs/VERSION/lisp,
                        share/emacs/VERSION/site-lisp, and
                        share/emacs/site-lisp via build-aux/update-subdirs
                        (Makefile.in:546-562, 695-696).
  * update-game-score sgid bit when --gameuser is set
                        (Makefile.in:856-864).

Static source-tree files (desktop/icons/manpages/metainfo.xml/
emacs.service) are installed by the meson DSL in meson.build itself.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


def copytree(src: Path, dst: Path, *, exclude: set[str] | None = None) -> None:
    exclude = exclude or set()
    for root, dirs, files in os.walk(src):
        rel = Path(root).relative_to(src)
        dirs[:] = [d for d in dirs if d not in exclude]
        out = dst / rel
        out.mkdir(parents=True, exist_ok=True)
        for f in files:
            if f in exclude:
                continue
            shutil.copy2(Path(root) / f, out / f)


def write_subdirs_el(directory: Path) -> None:
    """Write a top-level subdirs.el if one isn't already present.

    Mirrors `write_subdir` in Makefile.in:543-554.
    """
    target = directory / "subdirs.el"
    if target.exists():
        return
    directory.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "(if (fboundp 'normal-top-level-add-subdirs-to-load-path)\n"
        "    (normal-top-level-add-subdirs-to-load-path))\n"
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--prefix", required=True)
    p.add_argument("--bindir", required=True)
    p.add_argument("--datadir", required=True,
                   help="emacs share dir, e.g. share/emacs/31.0.50")
    p.add_argument("--libexecdir", required=True,
                   help="arch-specific dir holding emacs.pdmp + DOC")
    p.add_argument("--build-root", required=True, type=Path)
    p.add_argument("--source-root", required=True, type=Path)
    p.add_argument("--version", required=True)
    p.add_argument("--gameuser", default="",
                   help="user[:group] for sgid update-game-score")
    p.add_argument("--update-subdirs", required=True, type=Path,
                   help="path to build-aux/update-subdirs")
    args = p.parse_args()

    install_prefix = Path(
        os.environ.get("MESON_INSTALL_PREFIX", args.prefix)
    )
    destdir_prefix = Path(
        os.environ.get("MESON_INSTALL_DESTDIR_PREFIX", args.prefix)
    ).resolve()

    def resolve(p: str) -> Path:
        path = Path(p)
        if not path.is_absolute():
            return destdir_prefix / p
        try:
            rel = path.relative_to(install_prefix)
        except ValueError:
            return path
        return destdir_prefix / rel

    bindir = resolve(args.bindir)
    libexecdir = resolve(args.libexecdir)
    datadir = resolve(args.datadir)

    bindir.mkdir(parents=True, exist_ok=True)
    libexecdir.mkdir(parents=True, exist_ok=True)
    datadir.mkdir(parents=True, exist_ok=True)

    # --- emacs binary -------------------------------------------------
    # Installed as emacs-VERSION + an `emacs` symlink, matching
    # Makefile.in:585-595.
    emacs_bin = args.build_root / "src/emacs"
    if emacs_bin.exists():
        target = bindir / f"emacs-{args.version}"
        shutil.copy2(emacs_bin, target)
        target.chmod(0o755)
        link = bindir / "emacs"
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(target.name)
    else:
        print(f"warning: {emacs_bin} not built; skipping emacs install",
              file=sys.stderr)

    # --- emacs.pdmp ---------------------------------------------------
    # Lives at build/lisp/emacs.pdmp (it's defined under lisp/ because
    # of its dependency chain) -- but src/Makefile.in's bootstrap dump
    # also produces build/src/bootstrap-emacs.pdmp.  Prefer the lisp/
    # one since loadup.el ran with the byte-compiled tree.
    for candidate in (
        args.build_root / "lisp/emacs.pdmp",
        args.build_root / "src/emacs.pdmp",
    ):
        if candidate.exists():
            shutil.copy2(candidate, libexecdir / "emacs.pdmp")
            break

    # --- etc/DOC ------------------------------------------------------
    # Read by epaths.h's PATH_DOC at runtime.  Lives at
    # build/src/DOC, installs to libexec/emacs/VERSION/CONFIG/etc/DOC.
    # Reference: Makefile.in:701-714.
    doc_src = args.build_root / "src/DOC"
    if doc_src.exists():
        doc_dst = libexecdir / "etc"
        doc_dst.mkdir(parents=True, exist_ok=True)
        shutil.copy2(doc_src, doc_dst / "DOC")

    # --- lisp/ tree ---------------------------------------------------
    lisp_src = args.source_root / "lisp"
    lisp_dst = datadir / "lisp"
    if lisp_src.is_dir():
        copytree(lisp_src, lisp_dst,
                 exclude={"__pycache__", "Makefile.in", "Makefile"})

    # --- etc/ tree ----------------------------------------------------
    # The build-tree etc/ is the same as the source tree (we don't
    # generate anything there other than DOC, which already went to
    # libexecdir above).  Strip artefacts that the autotools install
    # also stripped (Makefile.in:678-689).
    etc_src = args.source_root / "etc"
    etc_dst = datadir / "etc"
    etc_strip_files = {
        "DOC",
        ".gitignore",
        ".arch-inventory",
        ".DS_Store",
    }
    etc_strip_globs = ("#", ".#", "ChangeLog")
    if etc_src.is_dir():
        for root, dirs, files in os.walk(etc_src):
            rel = Path(root).relative_to(etc_src)
            dirs[:] = [d for d in dirs if d != "__pycache__"]
            out = etc_dst / rel
            out.mkdir(parents=True, exist_ok=True)
            for f in files:
                if f in etc_strip_files:
                    continue
                if any(f.startswith(g) for g in etc_strip_globs):
                    continue
                if f.endswith("~") or f.endswith(".orig"):
                    continue
                shutil.copy2(Path(root) / f, out / f)

    # --- subdirs.el ---------------------------------------------------
    # build-aux/update-subdirs walks every direct subdirectory of its
    # argument and writes a subdirs.el there.  Mirrors
    # Makefile.in:691-696.
    if args.update_subdirs.exists() and lisp_dst.is_dir():
        try:
            subprocess.run(
                ["sh", str(args.update_subdirs), str(lisp_dst)],
                check=True,
            )
        except subprocess.CalledProcessError as e:
            print(
                f"warning: update-subdirs failed on {lisp_dst}: {e}",
                file=sys.stderr,
            )
    # share/emacs/VERSION/site-lisp and share/emacs/site-lisp need a
    # trivial subdirs.el so user-installed packages get picked up.
    write_subdirs_el(datadir / "site-lisp")
    parent_site = datadir.parent / "site-lisp"
    write_subdirs_el(parent_site)

    # --- native-comp .eln tree ---------------------------------------
    # When the build did native compilation, build/lisp/native-lisp is
    # the AOT cache.  Install under share/emacs/VERSION/native-lisp,
    # matching the autotools `install-eln` rule (Makefile.in:846-859).
    eln_src = args.build_root / "lisp/native-lisp"
    if eln_src.is_dir():
        copytree(eln_src, datadir / "native-lisp")

    # --- update-game-score sgid bit ----------------------------------
    # When --gameuser=USER_OR_GROUP is configured, the autotools build
    # uses `INSTALL_PROGRAM_GAME = $(INSTALL) -g $(gamegroup) -m 2755`
    # (lib-src/Makefile.in) -- group-only chgrp + sgid.  No chown.
    #
    # The meson option matches the autotools `--with-gameuser` form:
    #
    #   "user"        -> treated as a group name (legacy form)
    #   "user:group"  -> chgrp to `group`, optional chown to `user`
    #
    # Failures (DESTDIR staging where the user/group doesn't exist on
    # the build host) are warnings, not errors.
    if args.gameuser:
        ugs = libexecdir / "update-game-score"
        if ugs.exists():
            if ":" in args.gameuser:
                ugs_user, ugs_group = args.gameuser.split(":", 1)
            else:
                # Bare value: treat as group, like autotools' gamegroup.
                ugs_user, ugs_group = "", args.gameuser
            try:
                if ugs_user:
                    subprocess.run(
                        ["chown", ugs_user, str(ugs)], check=True,
                    )
                if ugs_group:
                    subprocess.run(
                        ["chgrp", ugs_group, str(ugs)], check=True,
                    )
                ugs.chmod(0o2755)
            except (subprocess.CalledProcessError, OSError) as e:
                print(
                    f"warning: could not chgrp/chown/sgid {ugs} to "
                    f"{args.gameuser}: {e}",
                    file=sys.stderr,
                )

    print(f"installed emacs {args.version} into {destdir_prefix}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
