#!/usr/bin/env python3
"""Post-build install script for the Emacs Meson build.

Handles items that need build-tree artefacts to exist on disk:

  * etc/DOC          -- generated by src/meson.build's etc-DOC target
                        (Makefile.in:701-714 install-etcdoc).
  * native-lisp/     -- *.eln tree from native-compilation
                        (Makefile.in:846-859 install-eln).
  * subdirs.el       -- generated under share/emacs/VERSION/lisp,
                        share/emacs/VERSION/site-lisp, and
                        share/emacs/site-lisp via build-aux/update-subdirs
                        (Makefile.in:546-562, 695-696).
  * update-game-score sgid bit when --gameuser is set
                        (Makefile.in:856-864).

Static source-tree files (desktop/icons/manpages/metainfo.xml/
emacs.service) are installed by the meson DSL in meson.build itself.
"""

from __future__ import annotations

import argparse
import gzip
import os
import shutil
import subprocess
import sys
from pathlib import Path


def gzip_file(src: Path) -> None:
    """Replace `src` with `src.gz` (gzip -9n -- no name/timestamp metadata)."""
    dst = src.with_suffix(src.suffix + ".gz")
    with src.open("rb") as fin, gzip.GzipFile(
        filename=str(dst),
        mode="wb",
        compresslevel=9,
        mtime=0,  # -n: no timestamp
    ) as fout:
        shutil.copyfileobj(fin, fout)
    src.unlink()


def copytree(src: Path, dst: Path, *, exclude: set[str] | None = None) -> None:
    exclude = exclude or set()
    for root, dirs, files in os.walk(src):
        rel = Path(root).relative_to(src)
        dirs[:] = [d for d in dirs if d not in exclude]
        out = dst / rel
        out.mkdir(parents=True, exist_ok=True)
        for f in files:
            if f in exclude:
                continue
            shutil.copy2(Path(root) / f, out / f)


def write_subdirs_el(directory: Path) -> None:
    """Write a top-level subdirs.el if one isn't already present.

    Mirrors `write_subdir` in Makefile.in:543-554.
    """
    target = directory / "subdirs.el"
    if target.exists():
        return
    directory.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "(if (fboundp 'normal-top-level-add-subdirs-to-load-path)\n"
        "    (normal-top-level-add-subdirs-to-load-path))\n"
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--prefix", required=True)
    p.add_argument("--bindir", required=True)
    p.add_argument("--datadir", required=True,
                   help="emacs share dir, e.g. share/emacs/31.0.50")
    p.add_argument("--libexecdir", required=True,
                   help="arch-specific dir holding emacs.pdmp + DOC")
    p.add_argument("--build-root", required=True, type=Path)
    p.add_argument("--source-root", required=True, type=Path)
    p.add_argument("--version", required=True)
    p.add_argument("--gameuser", default="",
                   help="user[:group] for sgid update-game-score")
    p.add_argument("--update-subdirs", required=True, type=Path,
                   help="path to build-aux/update-subdirs")
    p.add_argument("--compress-install", action="store_true",
                   help="gzip installed *.el / info / manpages "
                        "(matches autotools --with-compress-install)")
    p.add_argument("--mandir", default="",
                   help="installed manpage dir; required for --compress-install")
    p.add_argument("--infodir", default="",
                   help="installed info dir; required for --compress-install")
    p.add_argument("--gsettingsschemadir", default="",
                   help="installed GSettings schema dir for "
                        "glib-compile-schemas")
    args = p.parse_args()

    install_prefix = Path(
        os.environ.get("MESON_INSTALL_PREFIX", args.prefix)
    )
    destdir_prefix = Path(
        os.environ.get("MESON_INSTALL_DESTDIR_PREFIX", args.prefix)
    ).resolve()

    def resolve(p: str) -> Path:
        path = Path(p)
        if not path.is_absolute():
            return destdir_prefix / p
        try:
            rel = path.relative_to(install_prefix)
        except ValueError:
            return path
        return destdir_prefix / rel

    bindir = resolve(args.bindir)
    libexecdir = resolve(args.libexecdir)
    datadir = resolve(args.datadir)

    bindir.mkdir(parents=True, exist_ok=True)
    libexecdir.mkdir(parents=True, exist_ok=True)
    datadir.mkdir(parents=True, exist_ok=True)

    # --- emacs binary -------------------------------------------------
    # Installed as emacs-VERSION + an `emacs` symlink, matching
    # Makefile.in:585-595.
    emacs_bin = args.build_root / "src/emacs"
    if emacs_bin.exists():
        target = bindir / f"emacs-{args.version}"
        shutil.copy2(emacs_bin, target)
        target.chmod(0o755)
        link = bindir / "emacs"
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(target.name)
    else:
        print(f"warning: {emacs_bin} not built; skipping emacs install",
              file=sys.stderr)

    # --- emacs.pdmp ---------------------------------------------------
    # Lives at build/lisp/emacs.pdmp (it's defined under lisp/ because
    # of its dependency chain) -- but src/Makefile.in's bootstrap dump
    # also produces build/src/bootstrap-emacs.pdmp.  Prefer the lisp/
    # one since loadup.el ran with the byte-compiled tree.
    for candidate in (
        args.build_root / "lisp/emacs.pdmp",
        args.build_root / "src/emacs.pdmp",
    ):
        if candidate.exists():
            shutil.copy2(candidate, libexecdir / "emacs.pdmp")
            break

    # --- etc/DOC ------------------------------------------------------
    # Read by epaths.h's PATH_DOC at runtime.  Lives at
    # build/src/DOC, installs to libexec/emacs/VERSION/CONFIG/etc/DOC.
    # Reference: Makefile.in:701-714.
    doc_src = args.build_root / "src/DOC"
    if doc_src.exists():
        doc_dst = libexecdir / "etc"
        doc_dst.mkdir(parents=True, exist_ok=True)
        shutil.copy2(doc_src, doc_dst / "DOC")

    # --- lisp/ tree ---------------------------------------------------
    lisp_src = args.source_root / "lisp"
    lisp_dst = datadir / "lisp"
    if lisp_src.is_dir():
        copytree(lisp_src, lisp_dst,
                 exclude={"__pycache__", "Makefile.in", "Makefile"})

    # --- etc/ tree ----------------------------------------------------
    # The build-tree etc/ is the same as the source tree (we don't
    # generate anything there other than DOC, which already went to
    # libexecdir above).  Strip artefacts that the autotools install
    # also stripped (Makefile.in:678-689).
    etc_src = args.source_root / "etc"
    etc_dst = datadir / "etc"
    etc_strip_files = {
        "DOC",
        ".gitignore",
        ".arch-inventory",
        ".DS_Store",
    }
    etc_strip_globs = ("#", ".#", "ChangeLog")
    if etc_src.is_dir():
        for root, dirs, files in os.walk(etc_src):
            rel = Path(root).relative_to(etc_src)
            dirs[:] = [d for d in dirs if d != "__pycache__"]
            out = etc_dst / rel
            out.mkdir(parents=True, exist_ok=True)
            for f in files:
                if f in etc_strip_files:
                    continue
                if any(f.startswith(g) for g in etc_strip_globs):
                    continue
                if f.endswith("~") or f.endswith(".orig"):
                    continue
                shutil.copy2(Path(root) / f, out / f)

    # --- subdirs.el ---------------------------------------------------
    # build-aux/update-subdirs walks every direct subdirectory of its
    # argument and writes a subdirs.el there.  Mirrors
    # Makefile.in:691-696.
    if args.update_subdirs.exists() and lisp_dst.is_dir():
        try:
            subprocess.run(
                ["sh", str(args.update_subdirs), str(lisp_dst)],
                check=True,
            )
        except subprocess.CalledProcessError as e:
            print(
                f"warning: update-subdirs failed on {lisp_dst}: {e}",
                file=sys.stderr,
            )
    # share/emacs/VERSION/site-lisp and share/emacs/site-lisp need a
    # trivial subdirs.el so user-installed packages get picked up.
    write_subdirs_el(datadir / "site-lisp")
    parent_site = datadir.parent / "site-lisp"
    write_subdirs_el(parent_site)

    # --- native-comp .eln tree ---------------------------------------
    # When the build did native compilation, build/lisp/native-lisp is
    # the AOT cache.  Install under share/emacs/VERSION/native-lisp,
    # matching the autotools `install-eln` rule (Makefile.in:846-859).
    eln_src = args.build_root / "lisp/native-lisp"
    if eln_src.is_dir():
        copytree(eln_src, datadir / "native-lisp")

    # --- update-game-score chown/chgrp + suid/sgid bit ---------------
    # configure.ac:656-680 parses --with-gameuser=USER_OR_GROUP as:
    #
    #   bare `alice`  -> gameuser=alice,  gamegroup=        (USER mode)
    #   `:games`      -> gameuser=,       gamegroup=games   (GROUP mode)
    #   `yes`         -> gameuser=,       gamegroup=games   (GROUP mode)
    #   unset / empty -> not installed
    #
    # The autotools install rule then branches
    # (lib-src/Makefile.in:343-359):
    #
    #   USER mode:  chown ${gameuser};  chmod u+s,go-r  (mode 4711)
    #   GROUP mode: chgrp ${gamegroup}; chmod g+s,o-r  (mode 2751)
    #
    # DESTDIR-staged failures (user/group doesn't exist on the build
    # host) stay warnings rather than aborting the install.
    if args.gameuser:
        ugs = libexecdir / "update-game-score"
        if ugs.exists():
            if args.gameuser.startswith(":"):
                cmd, mode = (
                    ["chgrp", args.gameuser[1:], str(ugs)],
                    0o2751,
                )
            elif args.gameuser == "yes":
                # Default GROUP mode.
                cmd, mode = (
                    ["chgrp", "games", str(ugs)],
                    0o2751,
                )
            else:
                # USER mode: bare value.
                cmd, mode = (
                    ["chown", args.gameuser, str(ugs)],
                    0o4711,
                )
            try:
                subprocess.run(cmd, check=True)
                ugs.chmod(mode)
            except (subprocess.CalledProcessError, OSError) as e:
                print(
                    f"warning: could not apply gameuser="
                    f"{args.gameuser} to {ugs}: {e}",
                    file=sys.stderr,
                )

    # --- install-info dir index --------------------------------------
    # For every installed *.info file, register it in
    # "$infodir/dir" via `install-info --info-dir=...`.
    # Mirrors Makefile.in:733-754 install-info loop.
    if args.infodir:
        info_dst = resolve(args.infodir)
        if info_dst.is_dir():
            install_info = shutil.which("install-info")
            if install_info is None:
                print("warning: install-info not found; skipping info "
                      "dir registration", file=sys.stderr)
            else:
                for f in sorted(info_dst.iterdir()):
                    if f.is_file() and f.suffix == ".info":
                        try:
                            subprocess.run(
                                [install_info,
                                 "--info-dir=" + str(info_dst),
                                 str(f)],
                                check=False,  # warnings are common
                            )
                        except OSError as e:
                            print(f"warning: install-info {f}: {e}",
                                  file=sys.stderr)

    # --- glib-compile-schemas ----------------------------------------
    # When the build installed a gschema.xml, recompile the cache so
    # `gsettings get` finds it on the user's host.  Mirrors
    # Makefile.in:947-985.  Use the same dir meson installed the
    # schema into rather than hardcoding share/glib-2.0/schemas, so
    # custom -Ddatadir= configurations don't desync.
    if args.gsettingsschemadir:
        schemadir = resolve(args.gsettingsschemadir)
        if (schemadir / "org.gnu.emacs.defaults.gschema.xml").exists():
            glib_compile = shutil.which("glib-compile-schemas")
            if glib_compile is not None:
                try:
                    subprocess.run(
                        [glib_compile, str(schemadir)], check=False,
                    )
                except OSError as e:
                    print(
                        f"warning: glib-compile-schemas {schemadir}: {e}",
                        file=sys.stderr,
                    )

    # --- compress-install ---------------------------------------------
    # Autotools' --with-compress-install (default ON) gzip's installed
    # *.el files whose *.elc exists, info files, manpages, and
    # etc/publicsuffix.txt.  Reference: Makefile.in:678-732.
    if args.compress_install:
        # *.el next to a *.elc.
        for elc in lisp_dst.rglob("*.elc"):
            el = elc.with_suffix(".el")
            if el.exists():
                try:
                    gzip_file(el)
                except OSError as e:
                    print(f"warning: gzip {el}: {e}", file=sys.stderr)
        # etc/publicsuffix.txt.
        psl = etc_dst / "publicsuffix.txt"
        if psl.exists():
            try:
                gzip_file(psl)
            except OSError as e:
                print(f"warning: gzip {psl}: {e}", file=sys.stderr)
        # Info pages.
        if args.infodir:
            info_dst = resolve(args.infodir)
            if info_dst.is_dir():
                for info in info_dst.iterdir():
                    if info.is_file() and info.suffix != ".gz":
                        # Skip info-dir merge index.
                        if info.name == "dir":
                            continue
                        try:
                            gzip_file(info)
                        except OSError as e:
                            print(f"warning: gzip {info}: {e}",
                                  file=sys.stderr)
        # Manpages.
        if args.mandir:
            man_dst = resolve(args.mandir) / "man1"
            if man_dst.is_dir():
                for page in man_dst.glob("*.1"):
                    try:
                        gzip_file(page)
                    except OSError as e:
                        print(f"warning: gzip {page}: {e}",
                              file=sys.stderr)

    print(f"installed emacs {args.version} into {destdir_prefix}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
